// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gvvphfrxnckctewefekw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imd2dnBoZnJ4bmNrY3Rld2VmZWt3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg4OTg3ODQsImV4cCI6MjA3NDQ3NDc4NH0.S8knokVz8zSskEgM8a9ruRZZDA7O6wRe6MPsthwk6sA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});